using UnityEngine;

namespace SolarMajesty
{
    /// <summary>
    /// Built-in world profiles. Campaign order: Earth → Luna → Mars → Belt → Europa.
    /// </summary>
    public static class CelestialBodyCatalog
    {
        private static CelestialBodyProfile _earth;
        private static CelestialBodyProfile _luna;
        private static CelestialBodyProfile _mars;
        private static CelestialBodyProfile _belt;
        private static CelestialBodyProfile _europa;
        private static readonly CelestialBodyId[] AllBodies =
        {
            CelestialBodyId.Earth,
            CelestialBodyId.Luna,
            CelestialBodyId.Mars,
            CelestialBodyId.Belt,
            CelestialBodyId.Europa
        };

        public static CelestialBodyId[] All => AllBodies;
        public static CelestialBodyId Last => AllBodies[AllBodies.Length - 1];

        public static CelestialBodyProfile Earth() => _earth ??= BuildEarth();
        public static CelestialBodyProfile Luna() => _luna ??= BuildLuna();
        public static CelestialBodyProfile Mars() => _mars ??= BuildMars();
        public static CelestialBodyProfile Belt() => _belt ??= BuildBelt();
        public static CelestialBodyProfile Europa() => _europa ??= BuildEuropa();

        public static CelestialBodyProfile Get(CelestialBodyId id)
        {
            switch (id)
            {
                case CelestialBodyId.Earth: return Earth();
                case CelestialBodyId.Luna: return Luna();
                case CelestialBodyId.Mars: return Mars();
                case CelestialBodyId.Belt: return Belt();
                case CelestialBodyId.Europa: return Europa();
                default: return Luna();
            }
        }

        public static CelestialBodyId Next(CelestialBodyId id)
        {
            int n = ((int)id + 1) % AllBodies.Length;
            return AllBodies[n];
        }

        private static CelestialBodyProfile BuildEarth()
        {
            return new CelestialBodyProfile
            {
                Id = CelestialBodyId.Earth,
                DisplayName = "Earth",
                ShortCode = "EARTH",
                Briefing = "Empty drop. Colony Commons on the claim, HAB via airlocks. Soil creepers chew farms (F5). Hold pop 8, then Lunar Rocket.",
                ArrivalLog = "Earth drop confirmed. Claim disc live. Raise Colony Commons. Soil creepers follow the farms — Defend Area.",
                VictoryLog = "Earth secured. Lunar Rocket is on the pad — trajectory to Luna is open.",
                FailLog = "Earth outpost lost. Revive the robots or restart the drop.",
                EndlessLog = "Earth holds. Keep colonizing this crust — rating stands, no hop.",
                GroundLight = new Color(0.44f, 0.64f, 0.28f),
                GroundDark = new Color(0.18f, 0.30f, 0.12f),
                Horizon = new Color(0.62f, 0.76f, 0.86f),
                RockColor = new Color(0.40f, 0.36f, 0.30f),
                CraterRim = new Color(0.38f, 0.40f, 0.32f),
                CraterFloor = new Color(0.20f, 0.26f, 0.16f),
                DuneColor = new Color(0.52f, 0.48f, 0.26f),
                SoilNodeColor = new Color(0.44f, 0.32f, 0.16f),
                LairRim = new Color(0.20f, 0.10f, 0.08f),
                LairPit = new Color(0.08f, 0.05f, 0.04f),
                WaterDeep = new Color(0.08f, 0.28f, 0.48f),
                WaterShallow = new Color(0.22f, 0.58f, 0.64f),
                ForestCanopy = new Color(0.16f, 0.52f, 0.18f),
                ForestTrunk = new Color(0.32f, 0.18f, 0.08f),
                SkyTop = new Color(0.48f, 0.72f, 0.96f),
                SkyHorizon = new Color(0.88f, 0.92f, 0.97f),
                SunColor = new Color(1f, 0.97f, 0.90f),
                SunIntensity = 1.42f,
                SunEuler = new Vector3(38f, -32f, 0f),
                GradeFilter = new Color(0.98f, 1.00f, 1.04f),
                AmbientHum = 72f,
                FillColor = new Color(0.58f, 0.70f, 0.90f),
                AmbientSky = new Color(0.46f, 0.62f, 0.88f),
                AmbientEquator = new Color(0.40f, 0.50f, 0.34f),
                AmbientGround = new Color(0.10f, 0.14f, 0.08f),
                FogColor = new Color(0.76f, 0.86f, 0.94f),
                FogStart = 26f,
                FogEnd = 200f,
                AtmosphereThickness = 1.28f,
                SkyExposure = 1.32f,
                CraterCount = 0,
                RockCount = 36,
                DuneCount = 0,
                LakeCount = 8,
                RiverCount = 5,
                ForestPatchCount = 16,
                ResourceNodeCount = 10,
                LairCount = 3,
                CampusExclusion = 20f,
                MinSpacing = 8f,
                IcePolarBias = 0.25f,
                ResourceWeights = new[] { 4, 3, 3, 1 },
                LaunchTech = TechId.LunarRocket,
                PopulationGoal = 8,
                SustainHoldSeconds = 25f,
                ResearchRateMultiplier = 1.35f,
                StartRegolith = 110,
                StartWaterIce = 70,
                StartMetals = 340,
                StartPower = 120,
                ResupplyIntervalScale = 0.78f,
                ResupplyDockFee = 0,
                FreightMetals = 8,
                FreightIce = 4,
                OutpostPowerDraw = 2,
                CampusFaunaCap = 5,
                MiteSpawnWeight = 0.65f,
                LeechSpawnWeight = 1f,
                TickSpawnWeight = 0.2f,
                WispSpawnWeight = 0f,
                CreeperSpawnWeight = 1.65f,
                HopperSpawnWeight = 0f,
                FaunaCreeperTint = new Color(0.28f, 0.42f, 0.16f, 1f)
            };
        }

        private static CelestialBodyProfile BuildLuna()
        {
            return new CelestialBodyProfile
            {
                Id = CelestialBodyId.Luna,
                DisplayName = "Luna",
                ShortCode = "LUNA",
                Briefing = "Cratered grey. Ash hoppers press HABs (F2). Dust ticks on ore (F5). Hold pop 12, then Mars Ship.",
                ArrivalLog = "Luna insertion complete. Ash hoppers seek pressure at the HAB — Clear Threat. Dust ticks follow the mines.",
                VictoryLog = "Luna holds. Mars Ship staged. Next body: Mars.",
                FailLog = "Luna plaza is overrun. Revive or reseed this crater field.",
                EndlessLog = "Luna holds. Keep colonizing the craters — rating stands, no hop.",
                GroundLight = new Color(0.50f, 0.46f, 0.40f),
                GroundDark = new Color(0.34f, 0.31f, 0.28f),
                Horizon = new Color(0.22f, 0.20f, 0.19f),
                RockColor = new Color(0.28f, 0.26f, 0.24f),
                CraterRim = new Color(0.38f, 0.35f, 0.31f),
                CraterFloor = new Color(0.30f, 0.28f, 0.25f),
                DuneColor = new Color(0.42f, 0.39f, 0.34f),
                SoilNodeColor = new Color(0.52f, 0.48f, 0.40f),
                LairRim = new Color(0.18f, 0.08f, 0.08f),
                LairPit = new Color(0.08f, 0.04f, 0.05f),
                SkyTop = new Color(0.03f, 0.04f, 0.09f),
                SkyHorizon = new Color(0.28f, 0.24f, 0.20f),
                SunColor = new Color(1f, 0.94f, 0.86f),
                SunIntensity = 1.45f,
                SunEuler = new Vector3(48f, -35f, 0f),
                GradeFilter = new Color(0.94f, 0.96f, 1f),
                AmbientHum = 48f,
                FillColor = new Color(0.35f, 0.48f, 0.72f),
                AmbientSky = new Color(0.28f, 0.32f, 0.42f),
                AmbientEquator = new Color(0.22f, 0.20f, 0.18f),
                AmbientGround = new Color(0.12f, 0.10f, 0.09f),
                FogColor = new Color(0.55f, 0.52f, 0.48f),
                FogStart = 70f,
                FogEnd = 340f,
                AtmosphereThickness = 0.15f,
                SkyExposure = 0.55f,
                CraterCount = 96,
                RockCount = 140,
                DuneCount = 0,
                ResourceNodeCount = 24,
                LairCount = 8,
                CampusExclusion = 22f,
                MinSpacing = 9f,
                IcePolarBias = 0.55f,
                ResourceWeights = new[] { 5, 3, 2, 2 },
                LaunchTech = TechId.MarsShip,
                PopulationGoal = 12,
                SustainHoldSeconds = 40f,
                ResearchRateMultiplier = 1f,
                StartRegolith = 90,
                StartWaterIce = 55,
                StartMetals = 300,
                StartPower = 110,
                ResupplyIntervalScale = 1.11f,
                ResupplyDockFee = 4,
                FreightMetals = 16,
                FreightIce = 8,
                OutpostPowerDraw = 2,
                CampusFaunaCap = 5,
                MiteSpawnWeight = 0.25f,
                LeechSpawnWeight = 0.65f,
                TickSpawnWeight = 1.15f,
                WispSpawnWeight = 0f,
                CreeperSpawnWeight = 0f,
                HopperSpawnWeight = 1.7f,
                FaunaHopperTint = new Color(0.52f, 0.50f, 0.46f, 1f)
            };
        }

        private static CelestialBodyProfile BuildMars()
        {
            return new CelestialBodyProfile
            {
                Id = CelestialBodyId.Mars,
                DisplayName = "Mars",
                ShortCode = "MARS",
                Briefing = "Red dust. Wisps drain Power (F2); dust creepers chew farms (F5). Hold pop 16, then Belt Hauler.",
                ArrivalLog = "Mars descent. Dust wisps on Power — Clear Threat. Dust creepers on farms — Defend Area.",
                VictoryLog = "Mars holds. Belt Hauler is on the pad — trajectory into the rocks is open.",
                FailLog = "Mars outpost overwhelmed. The red plaza is not yours until the party stands.",
                EndlessLog = "Mars holds. Keep colonizing the red crust — rating stands, no hop.",
                GroundLight = new Color(0.82f, 0.42f, 0.18f),
                GroundDark = new Color(0.46f, 0.18f, 0.08f),
                Horizon = new Color(0.56f, 0.26f, 0.12f),
                RockColor = new Color(0.50f, 0.24f, 0.12f),
                CraterRim = new Color(0.64f, 0.32f, 0.14f),
                CraterFloor = new Color(0.34f, 0.14f, 0.07f),
                DuneColor = new Color(0.86f, 0.46f, 0.20f),
                SoilNodeColor = new Color(0.62f, 0.32f, 0.16f),
                LairRim = new Color(0.22f, 0.07f, 0.05f),
                LairPit = new Color(0.10f, 0.03f, 0.02f),
                SkyTop = new Color(0.62f, 0.36f, 0.18f),
                SkyHorizon = new Color(0.92f, 0.58f, 0.28f),
                SunColor = new Color(1f, 0.88f, 0.58f),
                SunIntensity = 1.52f,
                SunEuler = new Vector3(20f, -62f, 0f),
                GradeFilter = new Color(1.00f, 0.99f, 0.97f),
                AmbientHum = 58f,
                FillColor = new Color(0.90f, 0.88f, 0.86f),
                AmbientSky = new Color(0.58f, 0.52f, 0.48f),
                AmbientEquator = new Color(0.36f, 0.30f, 0.26f),
                AmbientGround = new Color(0.16f, 0.08f, 0.05f),
                FogColor = new Color(0.80f, 0.46f, 0.22f),
                FogStart = 28f,
                FogEnd = 190f,
                AtmosphereThickness = 1.08f,
                SkyExposure = 1.10f,
                CraterCount = 56,
                RockCount = 210,
                DuneCount = 64,
                ResourceNodeCount = 24,
                LairCount = 10,
                CampusExclusion = 22f,
                MinSpacing = 8.5f,
                IcePolarBias = 0.82f,
                ResourceWeights = new[] { 3, 5, 2, 2 },
                LaunchTech = TechId.BeltHauler,
                PopulationGoal = 16,
                SustainHoldSeconds = 50f,
                ResearchRateMultiplier = 0.9f,
                StartRegolith = 100,
                StartWaterIce = 65,
                StartMetals = 320,
                StartPower = 120,
                ResupplyIntervalScale = 1.33f,
                ResupplyDockFee = 6,
                FreightMetals = 22,
                FreightIce = 10,
                OutpostPowerDraw = 2,
                CampusFaunaCap = 6,
                MiteSpawnWeight = 0.7f,
                LeechSpawnWeight = 0.4f,
                TickSpawnWeight = 0.2f,
                WispSpawnWeight = 1.25f,
                CreeperSpawnWeight = 1.15f,
                HopperSpawnWeight = 0.55f,
                FaunaCreeperTint = new Color(0.62f, 0.32f, 0.14f, 1f),
                FaunaHopperTint = new Color(0.72f, 0.38f, 0.16f, 1f),
                FaunaWispTint = new Color(0.82f, 0.52f, 0.28f, 1f)
            };
        }

        private static CelestialBodyProfile BuildBelt()
        {
            return new CelestialBodyProfile
            {
                Id = CelestialBodyId.Belt,
                DisplayName = "Asteroid Belt",
                ShortCode = "BELT",
                Briefing = "No soil. Metal rush. Rock mites and ticks swarm mines (F5). Shard hoppers test the Commons (F2). Then Icebreaker.",
                ArrivalLog = "Belt insertion. Tether the Commons. Rock mites and ticks follow the ore — Defend Area. Shard hoppers raid HABs — Clear Threat.",
                VictoryLog = "Belt claim holds. Icebreaker staged — Europa's crust is next.",
                FailLog = "The rocks took the outpost. Revive the robots or abandon this cluster.",
                EndlessLog = "Belt claim holds. Keep stripping the rocks — rating stands, no hop.",
                GroundLight = new Color(0.22f, 0.20f, 0.18f),
                GroundDark = new Color(0.08f, 0.07f, 0.07f),
                Horizon = new Color(0.04f, 0.04f, 0.05f),
                RockColor = new Color(0.38f, 0.34f, 0.30f),
                CraterRim = new Color(0.28f, 0.26f, 0.24f),
                CraterFloor = new Color(0.12f, 0.11f, 0.10f),
                DuneColor = new Color(0.30f, 0.28f, 0.24f),
                SoilNodeColor = new Color(0.45f, 0.42f, 0.36f),
                LairRim = new Color(0.16f, 0.08f, 0.06f),
                LairPit = new Color(0.06f, 0.03f, 0.03f),
                SkyTop = new Color(0.01f, 0.01f, 0.02f),
                SkyHorizon = new Color(0.08f, 0.07f, 0.09f),
                SunColor = new Color(1f, 0.95f, 0.85f),
                SunIntensity = 1.55f,
                SunEuler = new Vector3(22f, 48f, 0f),
                GradeFilter = new Color(0.92f, 0.93f, 1f),
                AmbientHum = 38f,
                FillColor = new Color(0.22f, 0.24f, 0.32f),
                AmbientSky = new Color(0.08f, 0.09f, 0.14f),
                AmbientEquator = new Color(0.12f, 0.11f, 0.10f),
                AmbientGround = new Color(0.04f, 0.03f, 0.03f),
                FogColor = new Color(0.12f, 0.12f, 0.14f),
                FogStart = 40f,
                FogEnd = 220f,
                AtmosphereThickness = 0.04f,
                SkyExposure = 0.42f,
                CraterCount = 18,
                RockCount = 220,
                DuneCount = 0,
                ResourceNodeCount = 28,
                LairCount = 7,
                CampusExclusion = 16f,
                MinSpacing = 6.5f,
                IcePolarBias = 0.2f,
                ResourceWeights = new[] { 2, 7, 2, 4 },
                Kit = TerrainKit.AsteroidField,
                LaunchTech = TechId.Icebreaker,
                ExtractYieldScale = 1.35f,
                FarmYieldScale = 0.35f,
                MineYieldScale = 1.45f,
                PowerDrawScale = 1.1f,
                AsteroidIsletCount = 22,
                PopulationGoal = 10,
                SustainHoldSeconds = 35f,
                ResearchRateMultiplier = 1.05f,
                StartRegolith = 70,
                StartWaterIce = 40,
                StartMetals = 380,
                StartPower = 110,
                ResupplyIntervalScale = 1.67f,
                ResupplyDockFee = 8,
                FreightMetals = 30,
                FreightIce = 8,
                OutpostPowerDraw = 3,
                MoveSpeedScale = 1.18f,
                FaunaSpeedScale = 1.28f,
                FaunaAggroScale = 1.15f,
                CampusFaunaCap = 6,
                MiteSpawnWeight = 1.7f,
                LeechSpawnWeight = 0.35f,
                TickSpawnWeight = 1.6f,
                CreeperSpawnWeight = 0f,
                HopperSpawnWeight = 0.95f,
                PreferMineMites = true,
                LairStalkerBudget = 2,
                AmbientThreat = 0.10f,
                ExpansionThreat = 0.022f,
                FaunaMiteTint = new Color(0.38f, 0.32f, 0.28f, 1f),
                FaunaHopperTint = new Color(0.40f, 0.38f, 0.36f, 1f)
            };
        }

        private static CelestialBodyProfile BuildEuropa()
        {
            return new CelestialBodyProfile
            {
                Id = CelestialBodyId.Europa,
                DisplayName = "Europa",
                ShortCode = "EURO",
                Briefing = "Ice crust, radiation. Fissure leeches and ice wisps drain Power (F2). Ice creepers on farms (F5). Hold pop 14.",
                ArrivalLog = "Europa descent. Radiation outside the Commons. Fissure leeches and ice wisps on Power — Clear Threat. Ice creepers chew greenhouses — Defend Area.",
                VictoryLog = "Europa holds. Outer system is open. Oversee in sandbox or reseed this ice.",
                FailLog = "The crust took them. Revive, or the ice closes over the claim.",
                EndlessLog = "Europa holds. Keep colonizing the ice — rating stands, no hop.",
                GroundLight = new Color(0.78f, 0.88f, 0.92f),
                GroundDark = new Color(0.42f, 0.52f, 0.58f),
                Horizon = new Color(0.18f, 0.28f, 0.38f),
                RockColor = new Color(0.55f, 0.62f, 0.68f),
                CraterRim = new Color(0.62f, 0.72f, 0.78f),
                CraterFloor = new Color(0.32f, 0.42f, 0.52f),
                DuneColor = new Color(0.70f, 0.82f, 0.88f),
                SoilNodeColor = new Color(0.85f, 0.92f, 0.95f),
                LairRim = new Color(0.12f, 0.18f, 0.28f),
                LairPit = new Color(0.04f, 0.08f, 0.14f),
                WaterDeep = new Color(0.12f, 0.32f, 0.48f),
                WaterShallow = new Color(0.55f, 0.78f, 0.88f),
                SkyTop = new Color(0.06f, 0.10f, 0.22f),
                SkyHorizon = new Color(0.35f, 0.48f, 0.62f),
                SunColor = new Color(0.82f, 0.90f, 1f),
                SunIntensity = 0.85f,
                SunEuler = new Vector3(28f, 12f, 0f),
                GradeFilter = new Color(0.82f, 0.94f, 1f),
                AmbientHum = 44f,
                FillColor = new Color(0.35f, 0.55f, 0.75f),
                AmbientSky = new Color(0.22f, 0.32f, 0.48f),
                AmbientEquator = new Color(0.40f, 0.52f, 0.58f),
                AmbientGround = new Color(0.18f, 0.24f, 0.28f),
                FogColor = new Color(0.55f, 0.70f, 0.82f),
                FogStart = 35f,
                FogEnd = 200f,
                AtmosphereThickness = 0.22f,
                SkyExposure = 0.62f,
                CraterCount = 24,
                RockCount = 48,
                DuneCount = 0,
                LakeCount = 6,
                RiverCount = 5,
                ResourceNodeCount = 22,
                LairCount = 9,
                CampusExclusion = 20f,
                MinSpacing = 8f,
                IcePolarBias = 0.12f,
                ResourceWeights = new[] { 2, 2, 7, 3 },
                Kit = TerrainKit.IceCrust,
                LaunchTech = TechId.None,
                ExtractYieldScale = 1.15f,
                FarmYieldScale = 1.4f,
                MineYieldScale = 0.6f,
                PowerDrawScale = 1.55f,
                IcePlateCount = 16,
                PopulationGoal = 14,
                SustainHoldSeconds = 45f,
                ResearchRateMultiplier = 0.8f,
                StartRegolith = 80,
                StartWaterIce = 95,
                StartMetals = 260,
                StartPower = 150,
                ResupplyIntervalScale = 2f,
                ResupplyDockFee = 10,
                FreightMetals = 0,
                FreightIce = 0,
                OutpostPowerDraw = 3,
                MoveSpeedScale = 0.88f,
                RadiationDrainPerSecond = 0.012f,
                RadiationSafeRadius = 22f,
                FaunaSpeedScale = 0.92f,
                FaunaAggroScale = 1.22f,
                CampusFaunaCap = 6,
                MiteSpawnWeight = 0.3f,
                LeechSpawnWeight = 1.8f,
                TickSpawnWeight = 0f,
                WispSpawnWeight = 1.6f,
                CreeperSpawnWeight = 1.05f,
                HopperSpawnWeight = 0f,
                LairStalkerBudget = 3,
                AmbientThreat = 0.16f,
                ExpansionThreat = 0.02f,
                FaunaLeechTint = new Color(0.32f, 0.82f, 0.95f, 1f),
                FaunaCreeperTint = new Color(0.72f, 0.88f, 0.90f, 1f)
            };
        }
    }
}
